version: "3.8"

services:
  app:
    #container_name: django
    #hostname: django
    build:
      context: .
    ports: 
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"